classDiagram 
test --> ALM
ALM --> apl_alm_histo_p
ALM --> apl_alm_isom_p
ALM --> apl_alm_p
ALM --> apl_alm_popup_p
ALM --> lib_alm_dts_interface_p
ALM --> lib_alm_p
test --> APM
APM --> apl_apm_alm
APM --> apl_apm_cfg
APM --> apl_apm_data
APM --> apl_apm_tpl
APM --> lib_apm
APM --> lib_apm_dts_interface_p
APM --> lib_apm_stg_interface_p
APM --> apl_bac
APM --> apl_bac_alm
APM --> apl_bac_cfg
APM --> apl_bac_stg
APM --> lib_bac_stack_if
APM --> apl_bac_AnalogInput
APM --> apl_bac_BinaryInput
APM --> apl_bac_BinaryOutput
APM --> apl_bac_device
APM --> apl_bac_gw_device
