
classDiagram
    Programm --|> MBM

    MBM : apl_mbm_p
    MBM : apl_mbm_token
    MBM : apl_mbm_dts_interface
    
    MBM --|> apl_mbm_p
    MBM --|> apl_mbm_token
    MBM --|> apl_mbm_dts_interface

    apl_mbm_p : #includes
    apl_mbm_p : #include "MBB/lib_mbb.h"
    apl_mbm_p : #include "MBM/lib_mbm.h"
    apl_mbm_p : #include "TPL/lib_tpl.h"
    
    apl_mbm_p : AplMbmTokenSendForcedIs(teLibMbbCh zChannel) int
    apl_mbm_p : AplMbmTokenEthCompatibleIs(U8 zDeviceID) int
    apl_mbm_p : AplMbmGtwAvailableIs(void) int

    apl_mbm_p : AplMbmStatisticReset(void) int
    apl_mbm_p : AplMbmStatisticUpdate(tLibMbmRequest* zpRequest, tLibMbmResult* zpResult) int
    apl_mbm_p : AplMbmDeviceIDGet(U8 zMbsAddr, U32 zIPAddr) int
    apl_mbm_p : AplMbmGtwAvailableIs(void) int
    apl_mbm_p : AplMbmGtwAvailableIs(void) int
    apl_mbm_p : AplMbmGtwAvailableIs(void) int
    

